# Lesson 3: Linear Equations

In [1]:
import numpy as np

## Gauss Elimination with Partial Pivoting
Transforms a system into a simpler one by replacing equations by new ones obtained by multiplication and subtraction of equations from the original system.


In [2]:
def swap_for_largest_pivot(pivot_row, system):
    largest_pivot_row = pivot_row
    for row in range(pivot_row+1, len(system)):
        if system[row][pivot_row] > system[largest_pivot_row][pivot_row]:
            largest_pivot_row = row
    old_pivot_row = system[pivot_row].copy()
    system[pivot_row] = system[largest_pivot_row].copy()
    system[largest_pivot_row] = old_pivot_row

def forward_elimination(sys, naive=False):
    sys = np.array(sys, np.float64)
    # for pivot_row in range(0, len(sys) - 1):
    n = len(sys)
    for pivot_row in range(0, n-1):
        if not naive:
            swap_for_largest_pivot(pivot_row, sys)
        pivot = sys[pivot_row][pivot_row]
        # Reduce rest of rows
        for i in range(pivot_row+1, n):
            factor = sys[i][pivot_row] / pivot
            reduced_row = sys[i] - factor * sys[pivot_row]
            sys[i] = reduced_row
    return sys

def back_substitution(sys):
    n = len(sys)
    solution = [0] * n
    solution[n-1] = sys[n-1][n] / sys[n-1][n-1]
    for i in range(n-2, -1, -1):
        sum = sys[i][n]
        for j in range(i+1, n):
            sum -= sys[i][j] * solution[j]
        solution[i] = sum / sys[i][i]
    return solution

Usage:

In [3]:
system = [
    [3,    -2,    4,    -18 ],
    [-27,    17,     -31,    123 ],
    [-12,   9,    -14,    62 ]
]
forward_eliminated = forward_elimination(system)
print(forward_eliminated)
back_substituted = back_substitution(forward_eliminated)

print("\n| --- Solution --- |")
print(back_substituted)

[[  3.  -2.   4. -18.]
 [  0.   1.   2. -10.]
 [  0.   0.   7. -49.]]

| --- Solution --- |
[6.0, 4.0, -7.0]


## LU Decomposition

In [4]:
# Step 1
def lu_decomp(coefficient_matrix):
    n = len(coefficient_matrix)
    upper = np.array(coefficient_matrix, np.float64)
    lower = np.identity(n)
    
    for pivot_row in range(0, n-1):
        pivot = upper[pivot_row][pivot_row]
        # Reduce rest of rows
        for i in range(pivot_row+1, n):
            factor = upper[i][pivot_row] / pivot
            lower[i][pivot_row] = factor
            reduced_row = upper[i] - factor * upper[pivot_row]
            upper[i] = reduced_row
    return (lower, upper)

# Step 2
def forward_substitution(L, b):
    d = np.array([0]*len(b), np.float64)
    for row in range(len(b)):
        d[row] = b[row]
        for col in range(row):
            d[row] = d[row] - d[col]*L[row][col]
    return d
# Step 3
def naive_back_substitution(U, d):
    x = np.array(d, np.float64)
    for row in range(len(U)-1, -1, -1):
        for col in range(len(U[row])-1, row, -1):
            x[row] = x[row] - U[row][col]*x[col]
        x[row] = x[row] / U[row][row]
    return x

    # U = np.rot90(np.fliplr(U))
    # print(U)
    # d.reverse()
    # print(d)
    # return forward_substitution(U, d)
    # x = np.array([0]*len(d), np.float64)
    # for row in reversed(range(len(d))):
    #     x[row] = d[row]
    #     for col in range(len(d)-1, row+1, -1):
    #         x[row] = x[row] - x[col]*U[row][col]
    #     x[row] = x[row] / U[row][row]
    # return x
print(
    lu(
        [[-3,2,-1],[0,-2,5],[0,0,-2]],
        [-1, -9, 2]
    )
)




NameError: name 'lu' is not defined

# Scratchpad

In [ ]:
import numpy as np
from scipy.linalg import lu, solve
coeficient_matrix = [
    [2,1,3],
    [4,6,7],
    [2,9,7]
]
L, U = lu_decomp(coeficient_matrix)
print(U)
print(L)

print(
    forward_substitution(L, [-1, -7, -6])
)
# P = np.array([[0,1,0], [1,0,0], [0,0,1]], np.float64)
# A = np.array([[2, 7, -2], [3, -5, 2], [7, 4, -1]], np.float64)
# B = np.array([[7, 4, -1], [2, 7, -2], [3, -5, 2]], np.float64)
# print(P * A)

print("LU Decomp")
P, L, U = lu([[1,-2,3],[1,3,3],[3,14,28]])

print("P", P)
print("L", L)
print("U", U)


solve([[-3, 2, -1],[6,-6,7],[3,-4,4]],[-1,-7,-6])\

system = [
    [3,5,2,3],
    [9,20,16,3],
    [21,45,-36,3]
]
print("lksdjf",forward_elimination(system, True))